import { pool } from "../index.js";

const drugs = [
{"id":1,"drug_name":"Sertraline Hydrochloride","brand_name":"Sertraline Hydrochloride","cat_number":"9034196771","company":"Cipla Limited","dose_cost":"$604.69"},
{"id":2,"drug_name":"Titanium Dioxide, OCTINOXATE, Zinc Oxide","brand_name":"Luminous Goddess Aura Live Melting Foundation","cat_number":"6224129959","company":"TONYMOLY CO., LTD.","dose_cost":"$11.02"},
{"id":3,"drug_name":"HYDROCODONE BITARTRATE AND ACETAMINOPHEN","brand_name":"HYDROCODONE BITARTRATE AND ACETAMINOPHEN","cat_number":"5747914073","company":"Mallinckrodt, Inc.","dose_cost":"$613.16"},
{"id":4,"drug_name":"Montelukast Sodium","brand_name":"Montelukast Sodium","cat_number":"8879342320","company":"ReadyMeds","dose_cost":"$510.10"},
{"id":5,"drug_name":"Sodium fluoride","brand_name":"ACT Anticavity Fluoride Cinnamon","cat_number":"9462028605","company":"Chattem, Inc.","dose_cost":"$669.11"},
{"id":6,"drug_name":"ketamine hydrochloride","brand_name":"Ketalar","cat_number":"1942419473","company":"JHP Pharmaceuticals LLC","dose_cost":"$918.59"},
{"id":7,"drug_name":"Phenazopyridine","brand_name":"Phenazopyridine Hydrochloride","cat_number":"2146771631","company":"Rebel Distributors Corp","dose_cost":"$937.29"},
{"id":8,"drug_name":"Citalopram Hydrobromide","brand_name":"Citalopram Hydrobromide","cat_number":"7191886536","company":"Torrent Pharmaceuticals Limited","dose_cost":"$316.22"},
{"id":9,"drug_name":"Lorazepam","brand_name":"Lorazepam","cat_number":"9346080221","company":"Rebel Distributors Corp","dose_cost":"$472.68"},
{"id":10,"drug_name":"Pussy Willow","brand_name":"Pussy Willow","cat_number":"7637474690","company":"Nelco Laboratories, Inc.","dose_cost":"$908.42"},
{"id":11,"drug_name":"SAMBUCUS NIGRA FLOWER, CALENDULA OFFICINALIS FLOWER, ECHINACEA ANGUSTIFOLIA","brand_name":"FIRST AID","cat_number":"8040856051","company":"PUREMEDY","dose_cost":"$909.07"},
{"id":12,"drug_name":"fibrinogen human and thrombin human","brand_name":"TISSEEL","cat_number":"3517590320","company":"Baxter Healthcare Corporation","dose_cost":"$219.05"},
{"id":13,"drug_name":"OCTOCRYLENE AVOBENZONE OCTISALATE HOMOSALATE","brand_name":"Peter Island Continous sunscreen","cat_number":"0777535459","company":"Access Business Group LLC","dose_cost":"$607.25"},
{"id":14,"drug_name":"Progesterone","brand_name":"Progesterone","cat_number":"2220577899","company":"Akorn, Inc.","dose_cost":"$131.00"},
{"id":15,"drug_name":"Flumazenil","brand_name":"Flumazenil","cat_number":"4443061908","company":"Baxter Healthcare Corporation","dose_cost":"$50.65"},
{"id":16,"drug_name":"Alder, Red Alnus rubra","brand_name":"Pollens - Trees, Alder, Red Alnus rubra","cat_number":"1372375279","company":"Jubilant HollisterStier LLC","dose_cost":"$191.99"},
{"id":17,"drug_name":"Doxycycline Hyclate","brand_name":"Doxycycline Hyclate","cat_number":"9291973033","company":"Preferred Pharmaceuticals, Inc.","dose_cost":"$418.95"},
{"id":18,"drug_name":"Oxaliplatin","brand_name":"Oxaliplatin","cat_number":"3985752818","company":"Pfizer Laboratories Div Pfizer Inc.","dose_cost":"$628.46"},
{"id":19,"drug_name":"Alprazolam","brand_name":"Alprazolam","cat_number":"9794799610","company":"KAISER FOUNDATION HOSPITALS","dose_cost":"$635.76"},
{"id":20,"drug_name":"Avobenzone and Octinoxate","brand_name":"MANGO BUTTER LIPSTICK","cat_number":"3571882296","company":"ART COSMETICS SRL","dose_cost":"$966.21"},
{"id":21,"drug_name":"iloperidone","brand_name":"Fanapt","cat_number":"6483484666","company":"Vanda Pharmaceuticals Inc.","dose_cost":"$451.21"},
{"id":22,"drug_name":"methylphenidate hydrochloride","brand_name":"methylphenidate hydrochloride","cat_number":"3173041801","company":"American Health Packaging","dose_cost":"$830.70"},
{"id":23,"drug_name":"ALCOHOL","brand_name":"Harmon Face Values Warm Vanilla Sugar Scent Hand Sanitizer","cat_number":"8000520710","company":"Harmon Stores Inc.","dose_cost":"$664.91"},
{"id":24,"drug_name":"naproxen","brand_name":"Naprosyn","cat_number":"6466952630","company":"Genentech, Inc.","dose_cost":"$969.31"},
{"id":25,"drug_name":"Niacin","brand_name":"Niaspan","cat_number":"3827365902","company":"Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC","dose_cost":"$131.23"},
{"id":26,"drug_name":"Divalproex Sodium","brand_name":"Divalproex Sodium","cat_number":"4363602430","company":"Cardinal Health","dose_cost":"$271.92"},
{"id":27,"drug_name":"Chinese Elm","brand_name":"ULMUS PUMILA POLLEN","cat_number":"7081330444","company":"ALK-Abello, Inc.","dose_cost":"$185.64"},
{"id":28,"drug_name":"Triclosan","brand_name":"Creamy Peach Antibacterial Foaming Hand Wash","cat_number":"5374018337","company":"SJ Creations, Inc.","dose_cost":"$192.74"},
{"id":29,"drug_name":"Ferrum sidereum 6","brand_name":"Ferrum sidereum 6","cat_number":"3059167354","company":"Uriel Pharmacy Inc.","dose_cost":"$706.38"},
{"id":30,"drug_name":"Trifluoperazine Hydrochloride","brand_name":"Trifluoperazine Hydrochloride","cat_number":"3696441260","company":"Sandoz Inc","dose_cost":"$453.88"},
{"id":31,"drug_name":"Citrus limonum, Echinacea, Scrophularia nodosa, Teucrium Scorodonia, Baptisia tinctoria, Lobelia inflata, Phytolacca decandra, Pinus sylvestris, Zincum gluconicum, Thuja occidentalis, Capsicum annuum,","brand_name":"Lymph Drainage","cat_number":"1851663274","company":"Apothecfa Company","dose_cost":"$935.64"},
{"id":32,"drug_name":"Sulfur","brand_name":"Naturasil","cat_number":"8015519853","company":"Nature's Innovation, Inc.","dose_cost":"$663.87"},
{"id":33,"drug_name":"Anacardium orientale, Calcarea phosphorica, Carcinosin, Iodium, Stramonium, Tarentula hispana, Veratrum album","brand_name":"Progena","cat_number":"3168053104","company":"Meditrend, Inc. DBA Progena Professional Formulations","dose_cost":"$260.59"},
{"id":34,"drug_name":"Cetirizine Hydrochloride","brand_name":"Premier Value","cat_number":"2130655696","company":"Chain Drug Constortium","dose_cost":"$947.62"},
{"id":35,"drug_name":"Wheat Pollen","brand_name":"TRITICUM AESTIVUM POLLEN","cat_number":"7848290719","company":"ALK-Abello, Inc.","dose_cost":"$897.15"},
{"id":36,"drug_name":"Holly,","brand_name":"Bio Holly","cat_number":"0004215729","company":"Apotheca Company","dose_cost":"$296.95"},
{"id":37,"drug_name":"Duloxetine hydrochloride","brand_name":"Cymbalta","cat_number":"5604799610","company":"Aphena Pharma Solutions - Tennessee, LLC","dose_cost":"$988.64"},
{"id":38,"drug_name":"temazepam","brand_name":"temazepam","cat_number":"1444112880","company":"Bryant Ranch Prepack","dose_cost":"$985.16"},
{"id":39,"drug_name":"Cephalexin","brand_name":"Cephalexin","cat_number":"0972701044","company":"H.J. Harkins Company, Inc.","dose_cost":"$487.43"},
{"id":40,"drug_name":"witch hazel","brand_name":"Relief","cat_number":"5786515613","company":"H and P Industries, Inc. dba Triad Group","dose_cost":"$797.94"},
{"id":41,"drug_name":"Benzalkonium Chloride","brand_name":"Foaming Hand Sanitizer","cat_number":"3133290967","company":"Cintas Corp.","dose_cost":"$998.07"},
{"id":42,"drug_name":"Losartan Potassium","brand_name":"Losartan Potassium","cat_number":"0027364836","company":"Legacy Pharmaceutical Packaging","dose_cost":"$132.24"},
{"id":43,"drug_name":"POVIDONE-IODINE","brand_name":"MediChoice PVP Swabsticks","cat_number":"9756992816","company":"Owens and Minor","dose_cost":"$117.47"},
{"id":44,"drug_name":"Nitrous Oxide","brand_name":"Nitrous Oxide","cat_number":"6507156612","company":"Machine & Welding Supply Company","dose_cost":"$690.26"},
{"id":45,"drug_name":"Norethindrone Acetate","brand_name":"Aygestin","cat_number":"5882744733","company":"Teva Women's Health, Inc.","dose_cost":"$229.11"},
{"id":46,"drug_name":"Sterile Alcohol Prep Pad","brand_name":"Sterile Alcohol Prep Pad","cat_number":"5849149864","company":"Caribbean Medical Brokers","dose_cost":"$493.40"},
{"id":47,"drug_name":"acyclovir","brand_name":"Acyclovir","cat_number":"3178588132","company":"Mylan Pharmaceuticals Inc.","dose_cost":"$236.08"},
{"id":48,"drug_name":"Argentum Nitricum, Baptisia Tinctoria, Echinacea, Echinacea Purpurea, Galium Aparine, Phosphorus, Pulstilla, Sulphur, Thuma Occidentalis, Thymus Serpyllum","brand_name":"Stay Well","cat_number":"8079320608","company":"Alternative Pharmacy","dose_cost":"$334.58"},
{"id":49,"drug_name":"tobramycin","brand_name":"Tobrex","cat_number":"8876629475","company":"Rebel Distributors Corp","dose_cost":"$773.95"},
{"id":50,"drug_name":"Octinoxate and Titanium dioxide","brand_name":"PURE SHEER","cat_number":"4829545380","company":"NARS COSMETICS","dose_cost":"$955.70"},
{"id":51,"drug_name":"BENZALKONIUM CHLORIDE","brand_name":"BZK ANTISEPTIC TOWELETTE","cat_number":"7542427717","company":"Shanghai Yinjing Medical Supplies Co., Ltd.","dose_cost":"$367.35"},
{"id":52,"drug_name":"Pimecrolimus","brand_name":"ELIDEL","cat_number":"4896117409","company":"Valeant Pharmaceuticals North America LLC","dose_cost":"$382.43"},
{"id":53,"drug_name":"Parvovirus Nosode (B19)","brand_name":"Human Parvovirus Remedy","cat_number":"5139652811","company":"Deseret Biologicals, Inc","dose_cost":"$929.45"},
{"id":54,"drug_name":"Potassium Chloride","brand_name":"Klor-Con","cat_number":"6369525405","company":"Apace Packaging LLC","dose_cost":"$436.81"},
{"id":55,"drug_name":"Amoxicillin and Clavulanate Potassium","brand_name":"Amoxicillin and Clavulanate Potassium","cat_number":"1384281010","company":"Preferred Pharmaceuticals, Inc.","dose_cost":"$839.99"},
{"id":56,"drug_name":"dexamethasone","brand_name":"Dexamethasone","cat_number":"9052272298","company":"Preferred Pharmaceuticals, Inc","dose_cost":"$293.47"},
{"id":57,"drug_name":"PULLULARIA PULLULANS","brand_name":"AUREOBASIDIUM PULLULANS VAR PULLULANS","cat_number":"6853830350","company":"ALK-Abello, Inc.","dose_cost":"$290.09"},
{"id":58,"drug_name":"Triclosan","brand_name":"Witchs Brew Antibacterial Foaming Hand Wash","cat_number":"2760626172","company":"SJ Creations, Inc.","dose_cost":"$896.04"},
{"id":59,"drug_name":"fluvastatin sodium","brand_name":"LESCOL","cat_number":"6949794231","company":"Physicians Total Care, Inc.","dose_cost":"$93.38"},
{"id":60,"drug_name":"Acetaminophen, Asprin, Caffeine","brand_name":"Excedrin","cat_number":"5285005175","company":"Novartis Consumer Health, Inc","dose_cost":"$968.08"},
{"id":61,"drug_name":"DULOXETINE HYDROCHLORIDE","brand_name":"DULOXETINE","cat_number":"6416402904","company":"Golden State Medical Supply, Inc.","dose_cost":"$277.55"},
{"id":62,"drug_name":"Mugwort Common","brand_name":"ARTEMISIA VULGARIS POLLEN","cat_number":"0653069308","company":"ALK-Abello, Inc.","dose_cost":"$726.02"},
{"id":63,"drug_name":"HORSE CHESTNUT, COLLINSONIA CANADENSIS ROOT, HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK","brand_name":"Avenoc","cat_number":"9944930385","company":"Laboratoires Boiron","dose_cost":"$906.02"},
{"id":64,"drug_name":"Pine White","brand_name":"PINUS STROBUS POLLEN","cat_number":"3517882356","company":"ALK-Abello, Inc.","dose_cost":"$29.97"},
{"id":65,"drug_name":"Aluminum Chlorohydrate","brand_name":"Nuvel Softy Roll-on Antiperspirant Deodorant","cat_number":"4694765272","company":"Industrias Lavin de Mexico S.A. de C.V.","dose_cost":"$788.68"},
{"id":66,"drug_name":"Acyclovir","brand_name":"Acyclovir","cat_number":"4284892800","company":"Aidarex Pharmaceuticals LLC","dose_cost":"$961.33"},
{"id":67,"drug_name":"Botrytis cinerea","brand_name":"Botrytis","cat_number":"7988476572","company":"Allermed Laboratories, Inc.","dose_cost":"$990.84"},
{"id":68,"drug_name":"AVOBENZONE, OCTISALATE, OCTINOXATE, OCTOCRYLENE","brand_name":"CLARINS BROAD SPECTRUM SPF 15 SUNSCREEN DELECTABLE SELF TANNING MOUSSE","cat_number":"8491874003","company":"Laboratoires Clarins S.A.","dose_cost":"$956.62"},
{"id":69,"drug_name":"ZINC OXIDE","brand_name":"Badger Sport SPF 35 Sunscreen","cat_number":"5940921949","company":"Norwood Packaging Ltd.","dose_cost":"$887.98"},
{"id":70,"drug_name":"Nicotine Polacrilex","brand_name":"equaline nicotine","cat_number":"3967596184","company":"Supervalu Inc","dose_cost":"$574.29"},
{"id":71,"drug_name":"enoxaparin sodium","brand_name":"Enoxaparin sodium","cat_number":"1732012342","company":"Winthrop U.S.","dose_cost":"$625.43"},
{"id":72,"drug_name":"BACITRACIN, NEOMYCIN SULFATE, POLYMYXIN-B SULFATE","brand_name":"FACE VALUES TRIPLE ANTIBIOTIC","cat_number":"2650738421","company":"HARMON STORES INC.","dose_cost":"$661.29"},
{"id":73,"drug_name":"Pseudoephedrine Hydrochloride","brand_name":"Rugby Nasal Decongestant","cat_number":"7745833469","company":"Dispensing Solutions, Inc.","dose_cost":"$460.71"},
{"id":74,"drug_name":"Metformin Hydrochloride","brand_name":"Metformin Hydrochloride","cat_number":"2690097656","company":"Major Pharmaceuticals","dose_cost":"$771.03"},
{"id":75,"drug_name":"Sunscreen","brand_name":"Daily Fade","cat_number":"8806956906","company":"Biocosetic Research Labs","dose_cost":"$109.73"},
{"id":76,"drug_name":"Elm American","brand_name":"ULMUS AMERICANA POLLEN","cat_number":"1575802066","company":"ALK-Abello, Inc.","dose_cost":"$681.25"},
{"id":77,"drug_name":"Sodium Fluoride","brand_name":"Darby","cat_number":"1378386930","company":"Darby Dental Supply Co","dose_cost":"$602.03"},
{"id":78,"drug_name":"Benzalkonium Chloride","brand_name":"GenRx All Purpose Cleansing","cat_number":"9995466627","company":"PureTek Corporation","dose_cost":"$165.73"},
{"id":79,"drug_name":"ACETALDEHYDE","brand_name":"ACETALDEHYDE","cat_number":"0489909841","company":"HOMEOLAB USA INC.","dose_cost":"$924.56"},
{"id":80,"drug_name":"Triclosan","brand_name":"Fresh Linen Antibacterial Foaming Hand Wash","cat_number":"0147931592","company":"SJ Creations, Inc.","dose_cost":"$608.45"},
{"id":81,"drug_name":"Fucus Vesiculosus, Spongia Tosta, Iodium, Liothronine Sodium, Pulsatilla, Glandula Suprarenalis Suis, Pituitary (suis), Thryodinum (suis)","brand_name":"Thyroplex","cat_number":"1872294375","company":"BioActive Nutritional","dose_cost":"$457.08"},
{"id":82,"drug_name":"Cimetidine","brand_name":"Cimetidine","cat_number":"0199421668","company":"REMEDYREPACK INC.","dose_cost":"$20.50"},
{"id":83,"drug_name":"Ropinirole Hydrochloride","brand_name":"Ropinirole Hydrochloride","cat_number":"4657011197","company":"Heritage Pharmaceuticals Inc.","dose_cost":"$398.56"},
{"id":84,"drug_name":"Duloxetine Hydrochloride","brand_name":"Duloxetine Hydrochloride","cat_number":"3742543229","company":"Proficient Rx LP","dose_cost":"$511.14"},
{"id":85,"drug_name":"SODIUM MONOFLUOROPHOSPHATE","brand_name":"Colgate","cat_number":"0009605169","company":"Mission Hills S.A de C.V","dose_cost":"$706.17"},
{"id":86,"drug_name":"SODIUM MONOFLUOROPHOSPHATE","brand_name":"Colgate","cat_number":"8822859235","company":"Mission Hills, S.A. de C.V.","dose_cost":"$590.91"},
{"id":87,"drug_name":"ATORVASTATIN CALCIUM","brand_name":"ATORVASTATIN CALCIUM","cat_number":"3958468470","company":"Cardinal Health","dose_cost":"$21.82"},
{"id":88,"drug_name":"Avobenzone, Ensulizole, Octinoxate, and Oxybenzone","brand_name":"LBEL REGRESSION JOUR","cat_number":"2835656553","company":"Ventura International Ltd.","dose_cost":"$425.77"},
{"id":89,"drug_name":"Acetazolamide","brand_name":"AcetaZOLAMIDE","cat_number":"8467440279","company":"AvKARE, Inc.","dose_cost":"$589.61"},
{"id":90,"drug_name":"zinc acetate and zinc gluconate","brand_name":"Zicam","cat_number":"5590658705","company":"Matrixx Initiatives, Inc.","dose_cost":"$29.20"},
{"id":91,"drug_name":"Diethylpropion hydrochloride","brand_name":"Diethylpropion HCl Immediate-Release","cat_number":"8557355033","company":"PD-Rx Pharmaceuticals, Inc.","dose_cost":"$964.74"},
{"id":92,"drug_name":"TRICLOSAN","brand_name":"ANTIBACTERIAL","cat_number":"7234635947","company":"KMART CORPORATION","dose_cost":"$675.24"},
{"id":93,"drug_name":"voriconazole","brand_name":"VFEND","cat_number":"8991096247","company":"Roerig","dose_cost":"$476.70"},
{"id":94,"drug_name":"linezolid","brand_name":"Zyvox","cat_number":"9549974022","company":"Rebel Distributors Corp","dose_cost":"$313.15"},
{"id":95,"drug_name":"omeprazole, sodium bicarbonate","brand_name":"Zegerid","cat_number":"6731692360","company":"Physicians Total Care, Inc.","dose_cost":"$85.84"},
{"id":96,"drug_name":"pimecrolimus","brand_name":"Elidel","cat_number":"4986417223","company":"Physicians Total Care, Inc.","dose_cost":"$469.78"},
{"id":97,"drug_name":"Azithromycin","brand_name":"Azithromycin","cat_number":"1959788612","company":"Lake Erie Medical DBA Quality Care Products LLC","dose_cost":"$519.08"},
{"id":98,"drug_name":"Ibuprofen","brand_name":"Ibuprofen","cat_number":"7286468537","company":"NCS HealthCare of KY, Inc dba Vangard Labs","dose_cost":"$837.71"},
{"id":99,"drug_name":"Hydrochlorothiazide","brand_name":"Hydrochlorothiazide","cat_number":"5006124903","company":"Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC","dose_cost":"$352.82"},
{"id":100,"drug_name":"ONION","brand_name":"ALLIUM CEPA","cat_number":"8905716733","company":"Remedy Makers","dose_cost":"$628.02"}
];

async function populateTable() {
    for (let i = 0; i < drugs.length; i++) {
      const res = await pool.query(
        `INSERT INTO drugs (drug_name, brand_name, cat_number, company, dose_cost) VALUES ($1, $2, $3, $4, $5) RETURNING *;`,
        [drugs[i].drug_name, drugs[i].brand_name, drugs[i].cat_number, drugs[i].company, drugs[i].dose_cost]
      );
      console.log(res.rows[0].drug_name, "inserted");
    }
}
populateTable();